name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
#    tags: [ 'v*.*.*' ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Дозвіл на запис у GitHub Packages

    steps:
      # 1. Завантаження коду репозиторію
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      # 2. Налаштування Docker Buildx (необхідна для кешування через GHA)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c

      # 3. Логін у GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Генерація метаданих (тегів та лейблів) для Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Для гілки main
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }},event=push
            # Для тегів версій (v1.0.0)
            type=ref,event=tag
            # Latest тільки для release
            type=raw,value=latest,event=release

      # 5. Встановлення дати для BUILD_DATE
      - name: Get current date
        id: date
        run: echo "format_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT

      # 6. Збірка та пуш образу
      - name: Build and push Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          # Пушимо образ для 'push' та для 'release', але не для 'pull_request'
          push: ${{ github.event_name == 'push' || github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.format_date }}